services:
  postgres:
    image: postgres:16-alpine
    network_mode: host
    ports:
      - 5432:5432
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=oohlala
      - POSTGRES_DB=conway
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always
